Add test function
codezonediitj/pydatastructs pull request #535
Opened 2023-06-03 05:45 UTC by sak-codes

#### References to other Issues or PRs or Relevant literature

#### Brief description of what is fixed or changed

#### Other comments

2023-06-03 09:48 UTC, czgdp1807 reviewed
What is this for?

2023-06-03 11:05 UTC, czgdp1807 requested changes
Use it inside this PR.

2023-06-03 11:06 UTC, czgdp1807 requested changes
Upgrade it to 15 from 10.

https://github.com/codezonediitj/pydatastructs/blob/bab603f0b4f7571ef9a96f170412231b1a3d4752/.github/workflows/ci.yml#L145

2023-06-17 09:12 UTC, czgdp1807 requested changes
Following features should be added,

1. Benchmark tests should be run only when needed. `benchmark=False` should turn them off.
2. Benchmark tests if run should compulsorily accept an argument for benchmark size.
3.
```
>>> from pydatastructs import linear_data_structures as lds
>>> test(submodules=lds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/czgdp1807/codezonediitj/pydatastructs/pydatastructs/utils/test_util.py", line 43, in test
    for sub in submodules:
TypeError: 'module' object is not iterable
```

2023-06-22 17:06 UTC, sak-codes commented
I have tried to complete all the 3 features. Please see the output of last point:
```
>>> import pydatastructs as pyds
>>> from pydatastructs import linear_data_structures as lds
>>> pyds.test(lds)
============================= test session starts ==============================
platform darwin -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0
rootdir: /Users/thebigbool/repos/pydatastructs
plugins: cov-4.1.0, xdist-3.3.1, anyio-3.7.0
collected 31 items                                                             

pydatastructs/linear_data_structures/tests/test_arrays.py ...            [  9%]
pydatastructs/linear_data_structures/tests/test_linked_lists.py .....    [ 25%]
pydatastructs/linear_data_structures/tests/test_algorithms.py .......... [ 58%]
.............                                                            [100%]

============================== 31 passed in 0.10s ==============================
```

2023-06-28 05:11 UTC, Smit-create approved these changes
LGTM

2023-06-30 10:38 UTC, sak-codes commented on .github/workflows/ci.yml
> -          python -m pytest --doctest-modules --cov=./ --cov-report=xml -s
Coverage is handled already on line 46-56. So I didn't change that command.

2023-07-01 07:49 UTC, czgdp1807 approved these changes

2023-07-01 07:49 UTC, merged