C++ backend for Splay Trees
codezonediitj/pydatastructs pull request #562
Opened 2024-06-19 09:59 UTC by Kishan-Ved

Related to: Google Summer of Code 2024, Kishan Ved

### Objective
Add a C++ backend for Binary Indexed Trees class.

2024-06-25 13:22 UTC, czgdp1807 requested changes

2024-06-25 13:22 UTC, czgdp1807 commented on pydatastructs/trees/tests/test_binary_trees.py
> +    if(backend==Backend.PYTHON):
```suggestion
    if backend == Backend.PYTHON:
```

2024-06-25 13:22 UTC, czgdp1807 commented on pydatastructs/trees/tests/test_binary_trees.py
> +    if(backend==Backend.PYTHON):
```suggestion
    if backend == Backend.PYTHON:
```

2024-06-26 12:03 UTC, Kishan-Ved commented
I have made the mentioned changes.

2024-06-27 05:40 UTC, czgdp1807 approved these changes

2024-06-27 05:40 UTC, merged